exit.confirmation.title=EXIT CONFIRMATION
exit.confirmation.message=Are you sure you want to quit?
exit.confirmation.unsavedWarning=As of the current version, unsaved data will not be preserved.
exit.confirmation.quit=QUIT
exit.confirmation.return=RETURN
