package com.openrobotics.map;

import org.junit.jupiter.api.Test;
import java.util.UUID;
import static org.junit.jupiter.api.Assertions.*;

/**
 * Unit tests for {@link MapEntity}.
 *
 * <p>Validates both constructors, all getters, the name and position setters,
 * and the default no-op {@code update()} method.
 *
 * <p>Because {@link MapEntity} is not abstract we can instantiate it directly.
 */
public class MapEntityTest {

    /**
     * The (name, position) constructor should generate a non-null UUID automatically.
     */
    @Test
    public void testAutoUuidGenerated() {
        MapEntity entity = new MapEntity("E1", new Vector2D(0, 0));
        assertNotNull(entity.getId(), "Auto-generated UUID must not be null");
    }

    /**
     * The (name, position) constructor should store the provided name.
     */
    @Test
    public void testNameStoredByTwoArgConstructor() {
        MapEntity entity = new MapEntity("Shelf-A", new Vector2D(1, 2));
        assertEquals("Shelf-A", entity.getName());
    }

    /**
     * The (name, position) constructor should store the provided position.
     */
    @Test
    public void testPositionStoredByTwoArgConstructor() {
        Vector2D pos = new Vector2D(3, 7);
        MapEntity entity = new MapEntity("X", pos);
        assertEquals(pos, entity.getPosition());
    }

    /**
     * Two entities created without explicit UUIDs must receive distinct IDs.
     */
    @Test
    public void testAutoGeneratedUuidsAreUnique() {
        MapEntity a = new MapEntity("A", new Vector2D(0, 0));
        MapEntity b = new MapEntity("B", new Vector2D(0, 0));
        assertNotEquals(a.getId(), b.getId(), "Every entity must have a unique UUID");
    }

    /**
     * The explicit-UUID constructor should store the supplied UUID exactly.
     */
    @Test
    public void testExplicitUuidStored() {
        UUID id = UUID.fromString("00000000-0000-0000-0000-000000000001");
        MapEntity entity = new MapEntity(id, "E2", new Vector2D(5, 5));
        assertEquals(id, entity.getId());
    }

    /**
     * The explicit-UUID constructor should store name and position correctly.
     */
    @Test
    public void testExplicitConstructorStoresNameAndPosition() {
        UUID id = UUID.randomUUID();
        MapEntity entity = new MapEntity(id, "Rack-7", new Vector2D(9, 4));
        assertEquals("Rack-7", entity.getName());
        assertEquals(new Vector2D(9, 4), entity.getPosition());
    }

    /**
     * setName() should update the name returned by getName().
     */
    @Test
    public void testSetName() {
        MapEntity entity = new MapEntity("Old", new Vector2D(0, 0));
        entity.setName("New");
        assertEquals("New", entity.getName());
    }

    /**
     * setName(null) is currently allowed and stores null.
     */
    @Test
    public void testSetNameAllowsNull() {
        MapEntity entity = new MapEntity("Old", new Vector2D(0, 0));

        entity.setName(null);

        assertNull(entity.getName());
    }

    /**
     * setPosition() should update the position returned by getPosition().
     */
    @Test
    public void testSetPosition() {
        MapEntity entity = new MapEntity("E", new Vector2D(0, 0));
        entity.setPosition(new Vector2D(10, 20));
        assertEquals(new Vector2D(10, 20), entity.getPosition());
    }

    /**
     * setPosition(null) is currently allowed and stores null.
     */
    @Test
    public void testSetPositionAllowsNull() {
        MapEntity entity = new MapEntity("E", new Vector2D(0, 0));

        entity.setPosition(null);

        assertNull(entity.getPosition());
    }

    /**
     * The ID must be immutable; it cannot be changed via any public method.
     */
    @Test
    public void testIdIsImmutable() {
        UUID id = UUID.randomUUID();
        MapEntity entity = new MapEntity(id, "E", new Vector2D(0, 0));
        assertEquals(id, entity.getId(), "ID must not change after construction");
    }

    /**
     * Changing mutable fields must not affect the immutable ID.
     */
    @Test
    public void testSettersDoNotChangeId() {
        UUID id = UUID.randomUUID();
        MapEntity entity = new MapEntity(id, "E", new Vector2D(0, 0));

        entity.setName("Renamed");
        entity.setPosition(new Vector2D(9, 9));

        assertEquals(id, entity.getId());
    }

    /**
     * The constructors currently allow null name and position values.
     */
    @Test
    public void testConstructorsAllowNullFields() {
        MapEntity auto = new MapEntity(null, null);
        UUID id = UUID.randomUUID();
        MapEntity explicit = new MapEntity(id, null, null);

        assertNotNull(auto.getId());
        assertNull(auto.getName());
        assertNull(auto.getPosition());
        assertEquals(id, explicit.getId());
        assertNull(explicit.getName());
        assertNull(explicit.getPosition());
    }

    /**
     * The base update() hook must execute without throwing and must not
     * mutate visible state.
     */
    @Test
    public void testUpdateIsNoOp() {
        MapEntity entity = new MapEntity("E", new Vector2D(2, 3));
        String nameBefore = entity.getName();
        Vector2D posBefore = entity.getPosition();

        entity.update(null); // should be a no-op

        assertEquals(nameBefore, entity.getName());
        assertEquals(posBefore, entity.getPosition());
    }
}
